spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/rtl
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
  http:
    multipart.enabled=true 