spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rtl
    username: teamsm
    password: smproduct
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  http:
    multipart.enabled=true
